Added support for AD717x-AD411x family of devices
analogdevicesinc/pyadi-iio pull request #326
Opened 2022-04-27 10:56 UTC by jansunil

1) Added ad717x.py with supported parts and attributes
2) Added an example script for ad717x
3) Added a test script
4) Updated supported_parts.md
5) Updated __init__.py
6) Added adi.ad717x.rst

Signed-off-by: Janani Sunil <Janani.Sunil@analog.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A - Tested the ad717x_example.py with a 1.8v input at the analog inputs

**Test Configuration**:
* Hardware: EVAL-AD4111SDZ with the SDP-K1 board
* OS: Windows 10

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-27 11:12 UTC, jansunil commented
V2: Updated the spacing in docstrings

2022-05-02 03:50 UTC, jansunil commented
V3 Changes: Updated index.rst with ad717x

2022-05-02 04:07 UTC, jansunil commented
V4 Changes: Corrected spacing in code documentation

2022-05-02 04:11 UTC, jansunil commented
V5 Changes: Added a period at the end of the code documentation

2022-05-02 04:15 UTC, jansunil commented
V6 Changes: Added one line before and after class docstring, removed lines before and after function docstring

2022-05-02 04:21 UTC, jansunil commented
V7 Changes: Corrected syntax of constructor docstring

2022-05-02 05:54 UTC, jansunil commented
@tfcollins , Any review comments on this PR?

2022-05-10 08:54 UTC, tfcollins commented
Sorry for the delay. I was out a few weeks

2022-05-10 10:04 UTC, jansunil commented
Hi @tfcollins ,
Could you please help in understanding what the Lint test is all about? The details show that the 'black' step has failed, although it does not point to any line in the code.

2022-05-16 12:25 UTC, jansunil commented
Hi @tfcollins , 
Any inputs on the above build errors?

2022-05-21 01:32 UTC, tfcollins commented
Please run the precommit lint to fix the formatting issue

2022-05-23 04:27 UTC, jansunil commented
@tfcollins ,
Thanks for the link to the pre-commit step. The changes post execution of the command have been fixed.

2022-05-26 11:25 UTC, jansunil commented
@tfcollins ,

I do not see any specific comments within the code. Am I missing something ?

2022-05-26 16:24 UTC, tfcollins commented
> @tfcollins ,
> 
> I do not see any specific comments within the code. Am I missing something ?

Look above and in the PR changed files: https://github.com/analogdevicesinc/pyadi-iio/pull/326/files

2022-06-01 04:13 UTC, pmallick-adi commented on adi/__init__.py
> +
Does it support AD411x devices as well?

2022-06-01 14:11 UTC, tfcollins requested changes

2022-06-03 04:18 UTC, jansunil commented on adi/__init__.py
> +
Yes, it does.

2022-06-03 04:19 UTC, jansunil commented on supported_parts.md
> +- AD717x
Added actual part names

2022-06-03 04:19 UTC, jansunil commented on adi/ad717x.py
> +                raise Exception("Not a compatible device: " + device_name)
The string has been changed to an f-string

2022-06-03 04:19 UTC, jansunil commented on adi/ad717x.py
> +
Added a check for the mentioned variables

2022-06-03 04:20 UTC, jansunil commented on adi/ad717x.py
> +        return ret
A 'None' check has been added now

2022-06-03 04:20 UTC, jansunil commented on examples/ad717x_example.py
> +ad717x_dev.channel[0].raw
This line has been removed now

2022-06-06 23:30 UTC, tfcollins approved these changes

2022-06-07 00:31 UTC, merged