Add support for AD7768, and by extension, CN0501
analogdevicesinc/pyadi-iio pull request #344
Opened 2022-07-02 14:26 UTC by mthoren-adi

dma_tests.py: change np.sum to np.max to prevent rollover

Signed-off-by: Mark Thoren <mark.thoren@analog.com>

# Description

Add support for AD7768, 8-channel simultaneous sampling sigma-delta ADC.
dma_tests.py updated - using np.sum causes rollover to negative number in some circumstances.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How has this been tested?
**Test Configuration**:

* Hardware:
1: AD7768 Eval Board on Zed, CN0501
2: CN0501 on Cora Z7
Boot files for both are present on the 2021_r1/RC2 Kuiper image.
* OS: Windows 10
A pytest fixture tests DMA capture, as well as all writeable attributes (sample rate, filter type, power mode.)

# Documentation

All doc strings added to supported_parts.md, index.rst

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [XI have commented my code, particularly in hard-to-understand areas
- [X] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2022-07-02 14:32 UTC, mthoren-adi commented
@scuciurean, @tfcollins , most of this should be pretty straightforward. Please take a look at the channel initialization though:
[https://github.com/analogdevicesinc/pyadi-iio/pull/344/files#diff-432f14712e50c6d2efb6330cba77efcd043bf2f016409556712ec5d88773c579R64](url)
I think "probing" for channels (versus explicitly listing channel names) is probably a good practice for most multichannel parts, particularly if the number / name of channels can be changed via the device tree. In this case - I wanted to be prepared to add support for the AD7768-4, which is nearly identical but with only 4 channels.

2022-07-05 08:19 UTC, scuciurean commented
> 

Ad7768-1/-4 are using https://wiki.analog.com/resources/fpga/docs/util_cpack 

> @scuciurean, @tfcollins , most of this should be pretty straightforward. Please take a look at the channel initialization though: [https://github.com/analogdevicesinc/pyadi-iio/pull/344/files#diff-432f14712e50c6d2efb6330cba77efcd043bf2f016409556712ec5d88773c579R64](url) I think "probing" for channels (versus explicitly listing channel names) is probably a good practice for most multichannel parts, particularly if the number / name of channels can be changed via the device tree. In this case - I wanted to be prepared to add support for the AD7768-4, which is nearly identical but with only 4 channels.

2023-02-04 17:29 UTC, tfcollins requested changes

2023-02-04 17:29 UTC, tfcollins commented on adi/ad7768.py
> +        rx._rx_stack_interleaved = True  # DMA config. dependent. True for ad7768.
Can be removed. This doesn't do anything anymore

2023-02-04 17:29 UTC, tfcollins commented on adi/ad7768.py
> +        rx._rx_data_type = np.int32
Can you put this in the class definition

2023-02-04 17:29 UTC, tfcollins commented on adi/ad7768.py
> +# def _cast32(sample):
Remove commented block

2023-02-04 17:50 UTC, mthoren-adi commented
Thanks for the review @tfcollins , should be all set. Did a quick full-scale reality check to make sure nothing went awry with the data types:

![Capture](https://user-images.githubusercontent.com/36937756/216782026-e12914c2-48b7-4f10-887e-75a5b52218b6.PNG)

2023-02-04 18:54 UTC, merged