Cn0511 rebased
analogdevicesinc/pyadi-iio pull request #346
Opened 2022-07-05 08:03 UTC by VBeleca

# Description

- Added calibration of the output amplitude from 0 to 5.5GHz and exposed the raw attribute of the trim DAC (ad5693r) in adi/cn0511.py. 
 - Added an example of enabling and disabling the output as well as setting the calibrated output amplitude and frequency in adi.cn0511_example.py.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

To test these changes, examples/cn0511_example.py was run locally on a calibrated rpi+cn0511. The output of cn0511 was measured for different combinations of output powers and frequencies with Keysight spectrum analyzer N9030B.
 - test/test_cn0511_p.py needs to be updated.

**Test Configuration**:
* Hardware: cn0511+rpi
* OS: Kuiper Linux

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-05 13:22 UTC, VBeleca commented
Force push: a comment was modified in examples/cn0511_example.py and a typo was corrected in adi/cn0511.py at  "trim_frequency_raw" attribute.

2022-07-11 23:58 UTC, tfcollins commented
@VBeleca the main issue here is that we need libad9166+bindings installed in the CI system to even import the adi.ad9166 class. However, that requirement should be optional (similar to libad9361) since not everyone should need to install that library to use pyadi-iio itself.

After this https://github.com/analogdevicesinc/pyadi-iio/pull/351 is merged you can rebase to get the library on the linux side. However, since libad9166 doesn't have Windows builds you will still need to make importing libad9166 optional. Take a look here on an example with libad9361: 
https://github.com/analogdevicesinc/pyadi-iio/blob/master/adi/fmcomms5.py#L38
https://github.com/analogdevicesinc/pyadi-iio/blob/master/adi/fmcomms5.py#L80

2022-07-12 15:51 UTC, tfcollins commented on adi/cn0511.py
> +        #     print(gain, end=", ")
Please remove these comments

2022-07-12 15:53 UTC, tfcollins requested changes
Please be sure to run the precommit checks: https://analogdevicesinc.github.io/pyadi-iio/dev/index.html#precommit

2022-07-13 15:31 UTC, VBeleca commented on adi/cn0511.py
> +        #     print(gain, end=", ")
done

2022-07-13 15:32 UTC, VBeleca commented on adi/ad916x.py
> +import iio
done

2022-07-14 22:19 UTC, merged