Adding Support for CN0579
analogdevicesinc/pyadi-iio pull request #450
Opened 2023-07-04 10:55 UTC by nsacut

# Description

Created and tested Python Class, Example, and Test Scripts for AD7768-4.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Hardware used was EVAL-CN0579-ARDZ and Cora Z7 connected to laptop. Testing and development of python codes were done on a laptop running Windows 10.

**Test Configuration**:
* Hardware: EVAL-CN0579-ARDZ and Cora Z7
* OS: Windows 10

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have signed off all commits and they contain "Signed-off by: Nathaniel Acut <nathaniel.acut@analog.com>"
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-04 10:57 UTC, nsacut commented
Requesting a review from @tfcollins

2023-07-05 16:45 UTC, tfcollins commented on examples/cn0579/sin_params.py
This file already exists here: https://github.com/analogdevicesinc/pyadi-iio/blob/master/examples/ad4630/sin_params.py

2023-07-05 17:00 UTC, tfcollins commented on adi/cn0579.py
> +        self._set_iio_attr_int("voltage1", "raw", True, value, self._gpio)
Please add docstring

2023-07-05 17:00 UTC, tfcollins commented on adi/cn0579.py
> +        self._set_iio_attr_int("voltage2", "raw", True, value, self._gpio)
Please add docstring

2023-07-05 17:00 UTC, tfcollins commented on adi/cn0579.py
> +        self._set_iio_attr_int("voltage3", "raw", True, value, self._gpio)
Please add docstring

2023-07-05 17:01 UTC, tfcollins requested changes
Can you remove the comments for the lines that have the scaling if not used

2023-07-06 10:01 UTC, nsacut commented
> Can you remove the comments for the lines that have the scaling if not used

Yes, removed the commented lines for the unused scaling.

2023-07-10 18:14 UTC, tfcollins commented
Just fix the lint issue and we are good to merge

2023-07-11 15:32 UTC, tfcollins commented on examples/cn0579/cn0579_example.py
> +# Optionally passs URI as command line argument,
Lint is failing on this spelling mistake

2023-07-12 08:10 UTC, nsacut commented
> Lint issue not fixed yet

The commit https://github.com/analogdevicesinc/pyadi-iio/pull/450/commits/7f732822df135e96e7ef2c0d44589f47c92d7c64 should fix the remaining lint issues.

2023-07-18 07:08 UTC, nsacut commented
Hi @tfcollins, all checks are passing now. :)

2023-07-20 16:10 UTC, tfcollins approved these changes

2023-07-20 16:11 UTC, merged