Add support for LTC2672
analogdevicesinc/pyadi-iio pull request #558
Opened 2024-04-17 06:39 UTC by SaikiranGudla

# Description

Add ltc2672.py driver
Add test script, example code
Update index.rst, init.py, supported_parts.md files Add ltc2672 rst file

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* OS:

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-17 11:49 UTC, SaikiranGudla commented
Hi @tfcollins ,
This PR is ready to be reviewed.

2024-04-17 22:10 UTC, tfcollins commented on adi/ltc2672.py
> +    channel = []
**channel** should not be a class property or it needs to be reset within the constructor. This creates an issue when you have multiple instances of the class. channel will keep growing

2024-04-17 22:11 UTC, tfcollins commented on examples/ltc2672_example.py
> +from adi.ltc2672 import *
Please do not use * imports. Just import what you need

2024-04-17 22:12 UTC, tfcollins requested changes
Just a few minor changes

2024-04-18 11:23 UTC, SaikiranGudla commented
Change log: Addressed review comments

Import ltc2672 class in example file
Make channel an instance attribute instead of class attribute

2024-04-19 17:51 UTC, merged