adi:ad7134: Add support for ad7134
analogdevicesinc/pyadi-iio pull request #578
Opened 2024-06-14 03:50 UTC by jansunil

1. Add pyadi driver for ad405x family
2. Add example script for data capture with AD4052
3. Add documentation

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* OS:

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-19 04:01 UTC, jansunil commented
Changelog: Fixed pylint and build errors

2024-06-19 04:02 UTC, jansunil commented
@tfcollins  - Could you please review these changes when you get a chance?

2024-06-20 17:55 UTC, tfcollins commented on supported_parts.md
> +- AD4134
Please put these in numeric order

2024-06-20 17:56 UTC, tfcollins commented on adi/ad7134.py
> +# Copyright (C) 2024 Analog Devices, Inc.
Full license not needed. Just the SPDX

2024-06-20 17:57 UTC, tfcollins commented on adi/ad7134.py
> +    channel = []  # type: ignore
Should be called "channels". Needs to be reset/initialized in the constructor similar to the issue in the related PR

2024-06-20 17:57 UTC, tfcollins requested changes
Only minor issues to fix

2024-06-21 04:39 UTC, jansunil commented
Changelog: Addressed review comments
1) Corrected the license header
2) reword channel->channels
3) Ordered AD4134 in numeric order in the supported_parts.md

2024-06-22 04:55 UTC, jansunil commented
@tfcollins - Do these changes look good now?

2024-06-24 19:35 UTC, merged