adi:ad4170: Add support for ad4170
analogdevicesinc/pyadi-iio pull request #579
Opened 2024-06-14 04:01 UTC by jansunil

1. Add pyadi driver for ad4170 family
2. Add example script for data capture with ad4170
3. Add documentation

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* OS:

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-19 04:01 UTC, jansunil commented
Changelog: Fixed pylint and build errors

2024-06-19 04:02 UTC, jansunil commented
@tfcollins - Could you please review these changes when you get a chance?

2024-06-20 17:44 UTC, tfcollins commented on adi/ad4170.py
> +    channels = []  # type: ignore
This needs to be defined or reset (set to []) in the constructor. Otherwise you cannot use multiple instances of this class in the same session.

2024-06-20 17:45 UTC, tfcollins commented on adi/ad4170.py
> +        """Converts raw value to SI"""
Inputs need documentation

2024-06-20 17:45 UTC, tfcollins requested changes
Just some minor changes needed

2024-06-21 04:38 UTC, jansunil commented
Changelog: Addressed review comments
1) Added documentation for to_volts function
2) reset channels in the constructor

2024-06-22 04:54 UTC, jansunil commented
@tfcollins  - Do these changes look good now?

2024-06-24 19:31 UTC, tfcollins commented on adi/ad4170.py
> +# THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Sorry missed this the first time. This long form license can be removed. Just need the SPDX line

2024-06-24 19:35 UTC, tfcollins requested changes
Just license blurb update and we'll merge

2024-06-25 03:45 UTC, jansunil commented
Changelog: Address review comments
1) Correct the license header for ad4170.py
2) Rebase with analogdevicesinc/pyadi-iio/   main

2024-06-26 03:05 UTC, merged