ad7606 tweaks and updates
analogdevicesinc/pyadi-iio pull request #590
Opened 2024-08-19 09:16 UTC by commodo

# Description

This changeset mostly targets support for the AD7606C-18 and AD7606C-16 parts.

The upstream support for these parts is pending here:

https://lore.kernel.org/linux-iio/20240819064721.91494-1-aardelean@baylibre.com/T/#t

But there were a couple of fixes required for existing parts.

For one thing the oversampling attributes need to be made device-level attributes.

There are no 'range' attributes. These are scale attributes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Tested with a ZedBoard and an AD7606C-18 FMC board.
The HDL is a simplified version that uses the Zynq PS SPI controller, which kind of like using the AD7606 part directly connected to a simple RPi board; no fancy communication.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware: ZedBoard + AD7606C-18
* OS: Kuiper Linux + upstream IIO kernel + AD7606C-18/16 changes

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-22 23:02 UTC, tfcollins commented on adi/ad7606.py
> +        return None
If replacing with returns you can omit last line. Python always returns None if there is no explicit return statement

2024-08-22 23:02 UTC, tfcollins commented on adi/ad7606.py
> +            except:
Need an exception type

2025-02-24 22:00 UTC, tfcollins commented on adi/ad7606.py
> +            except Exception:
Bare expects should not be used. This should be a KeyError exception

2025-02-24 22:02 UTC, tfcollins commented on adi/ad7606.py
> +        except Exception:
Same as below. Catch only KeyError exceptions

2025-02-24 22:02 UTC, tfcollins requested changes
Just need an update on the bare exceptions

2025-03-02 09:49 UTC, commodo commented
> Just need an update on the bare exceptions

apologies for the delay;
updated;
thanks :)

2026-06-22 08:07 UTC, closed without merging