Add support for AD353xr
analogdevicesinc/pyadi-iio pull request #620
Opened 2024-12-10 07:18 UTC by SaikiranGudla

Add ad353xr.py driver
Add example script
Update index.rst, init.py, supported_parts.md files

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Hardware:
* OS:

# Documentation

If this is a new feature or example please mention or link any documentation. All new hardware interface classes require documentation.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have signed off all commits and they contain "Signed-off by: <insert name>"
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2025-02-17 20:07 UTC, tfcollins commented on adi/ad353xr.py
> +# All rights reserved.
Large license not required if you have the SPDX short identifier

2025-02-17 20:15 UTC, tfcollins commented on adi/ad353xr.py
> +        self.output_bits = []
What is this property? If its expected to be used by end users then it needs to be documented. Otherwise it should not be "public"

2025-02-17 20:27 UTC, tfcollins requested changes
Minor comments

2025-02-18 15:14 UTC, SaikiranGudla commented on adi/ad353xr.py
> +        self.output_bits = []
Yes, this gives the channel-wise number of output bits expected to be used by the end-user. Added the docstring as required!

2025-02-18 15:17 UTC, SaikiranGudla commented
> Minor comments

Resolved them!

2025-03-19 21:41 UTC, merged